services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - GLOBAL_LOG_LEVEL=INFO
      - AUDIT_LOG_LEVEL=REQUEST_RESPONSE
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  open-webui: {}
  pipelines: {}
